# deploy

name: Deploy App

on:
  workflow_dispatch:
    inputs:
      task:
        type: choice
        description: gradle task
        options: 
        - bundleProdDebug
        - assembleProdDebug

jobs:
  deploy:
    runs-on: macos-11

    env:
      KEYCHAIN: '/Library/Keychains/System.keychain'
      APPLE_KEY_ID: ${{ secrets.APPLE_KEY_ID }}
      APPLE_ISSUER_ID: ${{ secrets.APPLE_ISSUER_ID }}

    steps:
    - name: Show inputs
      run: |
        echo "task: ${{ github.event.inputs.task }}"

    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false

#    - name: Setup - Xcode
#      run: sudo xcode-select -s /Applications/Xcode_12.5.1.app

#    - name: Setup - Ruby and bundler dependencies
#      uses: ruby/setup-ruby@v1.57.0
#      with:
#        ruby-version: 2.4.0
#        bundler-cache: true

#    - name: Cache - cocoapods
#      uses: actions/cache@v2
#      with:
#        path: Pods
#        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
#        restore-keys: ${{ runner.os }}-pods-

#    - name: Install - cocoapods
#      run: pod install --repo-update

    - name: Keychain | p12
      uses: Apple-Actions/import-codesign-certs@v1
      with:
        p12-file-base64: ${{ secrets.CERTIFICATES_P12_BASE64 }}
        p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}

#    - name: Build
#      run: xcodebuild -workspace edx.xcworkspace -scheme edX -configuration Release archive -archivePath ./archive
#      run: xcodebuild -workspace edx.xcworkspace -scheme edX -sdk iphonesimulator

#    - name: Build
#      run: xcodebuild -configuration Release build
#    - name: Build | xcodebuild archive
#      run: set -o pipefail && xcodebuild -configuration Release archive -archivePath ./archive | xcpretty
#      run: xcodebuild -exportArchive -archivePath ./archive -exportPath ./build

    - run: echo "This job's status is ${{ job.status }}."
